spring:
  datasource:
    url: jdbc:mysql://beep-db-instance.c96ms6m44sen.ap-northeast-2.rds.amazonaws.com:3306/beepDatabase
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: beep_user
    password: qwer1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis
  data:
    redis:
      mail:
        host: redis # ?? ???? ???? ???? ?? ??
        port: 6379

  mail:
    username: heunseo9@gmail.com
    password: cyje eoaq uxsv upst
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp.auth: true
        smtp.timeout: 50000 # SMTP ??? ??? ???? ??? ???? ?? ??? 50,000ms
        smtp.starttls.enable: true

jwt:
  refresh-exp: 2592000000 #30일
  access-exp: 86400000 # 24시간
  prefix: Bearer
  header: Authorization
  secret-key: 5ef05a8c246eb343d8d94e777b56eb386d403be81cfeabba90035e429a4e808c

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
    path: /v3/api-docs

  default-consumes-media-type: application/json
  auto-tag-classes: true
  groups:
    enabled: false

  swagger-ui:
    operationsSorter: method
    path: /swagger-ui.html
