spring:
  datasource:
    url: jdbc:mysql://beep-db-instance.c96ms6m44sen.ap-northeast-2.rds.amazonaws.com:3306/beepDatabase
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: beep_user
    password: qwer1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cache:
    type: redis

  mail:
    username: heunseo9@gmail.com
    password: cyje eoaq uxsv upst
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp.auth: true
        smtp.timeout: 50000 # SMTP ??? ??? ???? ??? ???? ?? ??? 50,000ms
        smtp.starttls.enable: true

  data:
    redis:
#      token:
#        host: redis
#        port: 6379
      mail:
        host: redis # ?? ???? ???? ???? ?? ??
        port: 6379


jwt:
  refresh-exp: 2592000000
  access-exp: 60000
  prefix: Bearer
  header: Authorization
  secret-key: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY5ODA2OTUyMiwiaWF0IjoxNjk4MDY5NTIyfQ.HcGnidly9R-FK13BH40ETzgZx5JegHgUPAakQU0WP0A

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0 #사용하는 버전을 명시
    path: /v3/api-docs #api 문서 확인 경로, localhost:8080/v3/api-docs 로 접근

  default-consumes-media-type: application/json #기본으로 설정되는 미디어타입 지정
  auto-tag-classes: true #오토 태그 기능 활성화
  groups:
    enabled: false #api 그룹 기능, default는 true 이나 당장 사용하지 않기에 false 로 지정

  swagger-ui:
    operationsSorter: method #method 기준으로 정렬, 그외 alpha 로 정렬 가능
    path: /swagger-ui.html
