name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/beep .
      - name: Publish image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/beep:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: AWS Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # EC2 인스턴스 퍼블릭 DNS
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }} # pem 키
          script: |
            docker stop $(docker ps -a -q)
            docker rm $(docker ps --filter 'status=exited' -a -q)
            docker image prune -a -f
            
            docker pull ${{ secrets.DOCKER_USERNAME }}/beep:latest
            docker pull redis:

            docker run --name redis -p 6379:6379 --network redis-network -it -d redis
            
            docker run -d --name beep_redis redis

            docker run -d --name beep_app --log-driver=syslog -p 80:8080 \
              ${{ secrets.DOCKER_USERNAME }}/beep:latest
