name: CICD

on:
  push:
    branches: [deploy-to-ec2]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t 8bit/beep .
      - name: Publish image to docker hub
        run: docker push 8bit/beep:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image From Docker hub
        run: docker pull install 8bit/beep:latest
      - name: Delete old container
        run: docker rm -f beep-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 -e SPRING_PROFILES_ACTIVE=prod --name beep-container 8bit/beep