name: CICD

on:
  push:
    branches: [deploy-to-ec2]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/beep .
      - name: Publish image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/beep:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image From Docker hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/beep:latest
      - name: Delete old container
        run: docker rm -f beep-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 -e SPRING_PROFILES_ACTIVE=prod --name beep-container ${{ secrets.DOCKER_USERNAME }}/beep
